server:
  port: 8081

management:
  metrics:
    tags:
      job: spring_cloud_gateway_data
  endpoints:
    web:
      exposure:
        include: 'metrics,gateway,health,info,prometheus'

logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  profiles:
    active: ${spring.profiles.active}
  application:
    name: api-gateway

---

spring:
  config:
    activate:
      on-profile: "dev"
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:8200
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 290c8864349c10a1b625
            clientSecret: aaff6c9561986ea4e177fd675ac058e11b4e322e
  cloud:
    gateway:
      routes:
        - id: ecommerce.stats.dev
          uri: http://localhost:8082
          predicates:
            - Path=/api/e-commerce-stats/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: api.external.collector.dev
          uri: http://localhost:8083
          predicates:
            - Path=/api/ext-endpoint-collector/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
---

spring:
  config:
    activate:
      on-profile: "prod"
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://apmserver:8200
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 290c8864349c10a1b625
            clientSecret: aaff6c9561986ea4e177fd675ac058e11b4e322e
  cloud:
    gateway:
      routes:
        - id: ecommerce.stats.prod
          uri: http://${ecommerce.stats.service.name}:8082
          predicates:
            - Path=/api/${ecommerce.stats.service.name}/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: api.external.collector
          uri: http://${ext.endpoint.collector.service.name}:8083
          predicates:
            - Path=/api/${ext.endpoint.collector.service.name}/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
