server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: api_rewritepath_route
          uri: http://api.local:8082
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}